config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'cocktails#index'

  resources :cocktails, only: [:index, :show, :new, :create] do
    resources :doses, only: [:show, :new, :create]
  end
  resources :doses, only: [:destroy, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  validates :name, uniqueness: true, presence: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true

  validates :cocktail, presence: true, uniqueness: { scope: :ingredient }
  validates :ingredient, presence: true, uniqueness: { scope: :cocktail }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :select_cocktail, only: [:show]

  def index
    @cocktails = Cocktail.all
  end

  def show
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktails_path(@cocktail)
    else
      render :new
    end
  end

  private

  def select_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_cocktail, only: [:new, :create]

  def index
    @doses = Dose.all
  end

  def new
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @dose[:cocktail_id] = params[:cocktail_id]
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  def edit
    @dose = Dose.find(params[:id])
  end

  def update
    @dose = Dose.find(params[:id])
    @dose.update(dose_params)
    if @dose.save
      redirect_to cocktail_path(@dose.cocktail)
    else
      render :edit
    end
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<h1>Cocktails List</h1>

<ul>
  <% @cocktails.each do |cocktail| %>
  <li><%= link_to cocktail.name, cocktail_path(cocktail)%></li>
  <% end %>
</ul>

<%= link_to "create new cocktail", new_cocktail_path, class: "btn btn-primary" %>

app/views/cocktails/new.html.erb
<div class="container">
  <h1>Create new form</h1>
  <%= simple_form_for @cocktail do |f| %>
    <%= f.input :name %>
    <%= f.submit "Submit", class: "btn btn-primary" %>
    <%= link_to "back", cocktails_path, class: "btn btn-primary" %>
  <% end %>
</div>

app/views/cocktails/show.html.erb
<h1>Cocktail details</h1>

<h2><%= @cocktail.name %></h2>

<ul>
  <% @cocktail.doses.each do |dose| %>
  <li><%= dose.ingredient.name %> | <%= dose.description %> |
    <%= link_to "delete", dose_path(dose), method: :delete %> |
    <%= link_to "edit", edit_dose_path(dose) %></li>
  <% end %>
</ul>

<%= link_to "return", cocktails_path, class: "btn btn-primary" %>
<%= link_to "add ingredient", new_cocktail_dose_path(@cocktail), class: "btn btn-primary" %>

app/views/doses/edit.html.erb
<h1>Edit ingredient</h1>

<%= simple_form_for ([@cocktail, @dose]) do |f| %>
  <%= f.input :description %>
  <%= f.association :ingredient %>
  <%= f.submit "Submit", class: "btn btn-primary" %>
  <%= link_to "cancel", cocktail_dose_path(@dose), class: "btn btn-primary" %>
<% end %>

app/views/doses/new.html.erb
<h1> Add ingredients</h1>

<%= simple_form_for ([@cocktail, @dose]) do |f| %>
  <%= f.input :description %>
  <%= f.association :ingredient %>
  <%= f.submit "Submit", class: "btn btn-primary" %>
  <%= link_to "cancel", cocktail_path(@cocktail), class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag "application" %>
    <%= javascript_pack_tag "application" %>
  </body>
</html>